import type { FieldSpec, OrderField, ReportField } from "./types";

/**
 * Header aliases seen in real exports. Aliases are matched against the
 * normalized header (lowercase, unaccented, single-spaced), so list them in
 * that form. Sellers use Shopify, WooCommerce, Google Sheets and hand-typed
 * Excel — in French, English, and transliterated Darija — so this table is
 * what makes the importer feel like it "just knows" their file.
 */

export const ORDER_FIELD_SPECS: FieldSpec<OrderField>[] = [
  {
    field: "reference",
    label: "N° de commande",
    required: true,
    hint: "Ton identifiant de commande, ex. CMD-2231",
    aliases: [
      "reference",
      "ref",
      "commande",
      "n commande",
      "no commande",
      "num commande",
      "numero commande",
      "numero de commande",
      "order",
      "order id",
      "order number",
      "order name",
      "id commande",
      "id",
      "code",
    ],
  },
  {
    field: "customerName",
    label: "Client",
    required: true,
    aliases: [
      "client",
      "nom",
      "nom client",
      "nom du client",
      "customer",
      "customer name",
      "billing name",
      "shipping name",
      "destinataire",
      "nom complet",
      "full name",
    ],
  },
  {
    field: "phone",
    label: "Téléphone",
    required: true,
    hint: "Sert à rapprocher les lignes du courier",
    aliases: [
      "telephone",
      "tel",
      "phone",
      "gsm",
      "mobile",
      "numero",
      "num tel",
      "numero de telephone",
      "billing phone",
      "shipping phone",
      "customer phone",
      "contact",
    ],
  },
  {
    field: "city",
    label: "Ville",
    required: true,
    aliases: [
      "ville",
      "city",
      "billing city",
      "shipping city",
      "destination",
      "madina",
    ],
  },
  {
    field: "address",
    label: "Adresse",
    required: false,
    aliases: [
      "adresse",
      "address",
      "address 1",
      "billing address",
      "shipping address",
      "billing address 1",
      "shipping address 1",
      "rue",
    ],
  },
  {
    field: "productName",
    label: "Produit",
    required: false,
    aliases: [
      "produit",
      "product",
      "article",
      "designation",
      "lineitem name",
      "line item name",
      "item",
      "nom produit",
      "product name",
      "titre",
    ],
  },
  {
    field: "productSku",
    label: "SKU produit",
    required: false,
    aliases: ["sku", "code produit", "ref produit", "lineitem sku", "product sku", "variant sku"],
  },
  {
    field: "quantity",
    label: "Quantité",
    required: false,
    aliases: ["quantite", "qte", "qty", "quantity", "lineitem quantity", "nombre"],
  },
  {
    field: "totalAmount",
    label: "Montant COD",
    required: true,
    hint: "Le montant à encaisser chez le client",
    aliases: [
      "montant",
      "prix",
      "total",
      "montant total",
      "prix total",
      "cod",
      "montant cod",
      "total price",
      "amount",
      "price",
      "valeur",
      "somme",
      "thaman",
    ],
  },
  {
    field: "courier",
    label: "Courier",
    required: false,
    aliases: ["courier", "coursier", "livreur", "transporteur", "carrier", "societe livraison", "shipping company"],
  },
  {
    field: "trackingNumber",
    label: "N° de suivi",
    required: false,
    hint: "Le meilleur moyen de rapprocher — mappe-le si tu l'as",
    aliases: [
      "tracking",
      "tracking number",
      "suivi",
      "n suivi",
      "no suivi",
      "numero suivi",
      "numero de suivi",
      "code barre",
      "barcode",
      "colis",
      "awb",
      "bl",
    ],
  },
  {
    field: "status",
    label: "Statut",
    required: false,
    aliases: ["statut", "status", "etat", "situation", "fulfillment status"],
  },
  {
    field: "orderedAt",
    label: "Date de commande",
    required: false,
    aliases: [
      "date",
      "date commande",
      "date de commande",
      "created at",
      "order date",
      "date creation",
    ],
  },
];

export const REPORT_FIELD_SPECS: FieldSpec<ReportField>[] = [
  {
    field: "trackingNumber",
    label: "N° de suivi",
    required: false,
    hint: "Le rapprochement le plus fiable",
    aliases: [
      "tracking",
      "tracking number",
      "suivi",
      "n suivi",
      "no suivi",
      "numero suivi",
      "numero de suivi",
      "code barre",
      "barcode",
      "colis",
      "n colis",
      "awb",
      "bl",
      "cab",
    ],
  },
  {
    field: "reference",
    label: "N° de commande",
    required: false,
    aliases: [
      "reference",
      "ref",
      "ref commande",
      "commande",
      "order",
      "order id",
      "n commande",
      "numero commande",
      "code",
    ],
  },
  {
    field: "phone",
    label: "Téléphone",
    required: false,
    aliases: ["telephone", "tel", "phone", "gsm", "mobile", "numero", "destinataire tel"],
  },
  {
    field: "customerName",
    label: "Client",
    required: false,
    aliases: ["client", "nom", "destinataire", "customer", "nom client"],
  },
  {
    field: "city",
    label: "Ville",
    required: false,
    aliases: ["ville", "city", "destination", "zone"],
  },
  {
    field: "courier",
    label: "Courier",
    required: false,
    hint: "Si le fichier mélange plusieurs couriers, mappe cette colonne",
    aliases: [
      "courier",
      "coursier",
      "livreur",
      "transporteur",
      "carrier",
      "societe",
      "societe livraison",
      "shipping company",
      "operateur",
      "prestataire",
    ],
  },
  {
    field: "status",
    label: "Statut livraison",
    required: true,
    hint: "Livré, retourné, refusé…",
    aliases: [
      "statut",
      "status",
      "etat",
      "etat colis",
      "situation",
      "statut livraison",
      "etat livraison",
      "resultat",
      "delivery status",
    ],
  },
  {
    field: "codAmount",
    label: "Montant COD",
    required: false,
    hint: "Le montant que le courier devait encaisser",
    aliases: [
      "cod",
      "montant cod",
      "montant",
      "valeur",
      "prix",
      "montant colis",
      "amount",
      "cod amount",
      "total",
    ],
  },
  {
    field: "paidAmount",
    label: "Montant versé",
    required: false,
    hint: "Ce que le courier t'a réellement versé",
    aliases: [
      "montant verse",
      "verse",
      "paye",
      "montant paye",
      "paid",
      "paid amount",
      "reglement",
      "montant reglement",
      "net a payer",
      "net paye",
      "montant net",
      "encaisse",
      "montant encaisse",
      "virement",
    ],
  },
  {
    field: "fee",
    label: "Frais courier",
    required: false,
    aliases: [
      "frais",
      "frais livraison",
      "frais de livraison",
      "tarif",
      "commission",
      "fee",
      "fees",
      "charge",
      "frais retour",
    ],
  },
  {
    field: "reportDate",
    label: "Date",
    required: false,
    aliases: [
      "date",
      "date livraison",
      "date de livraison",
      "date reglement",
      "date operation",
      "delivery date",
      "date statut",
    ],
  },
];
